MarketPlace.Application/Models/ErrorViewModel.cs
namespace MarketPlace.Application.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MarketPlace.Application/Controllers/AccountController.cs
using MarketPlace.Business.Modules.Auth;
using MarketPlace.Data.DataObjects.Auth;
using Microsoft.AspNetCore.Mvc;

namespace MarketPlace.Application.Controllers
{
    public class AccountController : Controller
    {
        private readonly IAccountService _service;

        public AccountController(IAccountService service)
        {
            _service = service;
        }

        public async Task<IActionResult> SignOut()
        {
            await _service.SignOut();
            return RedirectToAction("Index","Home");
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View(new LoginViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if(!ModelState.IsValid) 
            {
                model.Errors.Add(ModelState.Values.SelectMany(x => x.Errors).FirstOrDefault().ErrorMessage);
                return View(model);
            }
            var result = await _service.Login(model);
            if (result.Status)
            {
                return RedirectToAction("Index", "Home");
            }
            model.Errors.Add(result.Message);
            return View(model);
        }

        [HttpGet]
        public IActionResult Register(string code)
        {
            RegisterViewModel model = new() { WhoReferredMeCode = code };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Errors.Add(ModelState.Values.SelectMany(x => x.Errors).FirstOrDefault().ErrorMessage);
                return View(model);
            }
            var result = await _service.Register(model);
            if(result.Success)
            {
                return View("Login", new LoginViewModel { Email = model.Email });
            }
            return View(model);
        }
    }
}

MarketPlace.Application/Controllers/BuyController.cs
using MarketPlace.Business.Modules.Purchase;
using Microsoft.AspNetCore.Mvc;

namespace MarketPlace.Application.Controllers
{
    public class BuyController : Controller
    {

        private readonly IBuyService _service;

        public BuyController(IBuyService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var productTypes = await _service.FetchProductTypes();
            return View(productTypes);
        }
    }
}

MarketPlace.Application/Controllers/HomeController.cs
using MarketPlace.Application.Models;
using MarketPlace.Business.Modules.KycModule;
using MarketPlace.Data.DataObjects.KycModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace MarketPlace.Application.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IKycService _kycService;

        public HomeController(ILogger<HomeController> logger, IKycService kycService)
        {
            _logger = logger;
            _kycService = kycService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Profile()
        {
            var kyc = await _kycService.Get();
            return View(kyc);
        }

        [HttpPost]
        public async Task<IActionResult> UploadPassport(IFormFile file)
        {
            var result = await _kycService.UploadPassport(file);
            return Json(result);
        }


        [HttpPost]
        public async Task<IActionResult> SaveProfile([FromBody]ProfileDto model)
        {
            var result = await _kycService.SaveProfile(model);
            return Json(result);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MarketPlace.Application/Controllers/LocationController.cs
using MarketPlace.Business.Modules.Location;
using Microsoft.AspNetCore.Mvc;

namespace MarketPlace.Application.Controllers
{
    public class LocationController : Controller
    {
        private readonly ILocationService _service;

        public LocationController(ILocationService service)
        {
            _service = service;
        }
    }
}

MarketPlace.Application/Views/Buy/Index.cshtml
@model MarketPlace.Data.DataObjects.Common.NameCount

<div class="d-flex align-items-start">
    <div class="nav flex-column nav-pills me-3" id="v-pills-tab" role="tablist" aria-orientation="vertical">
        <button class="nav-link active" id="v-pills-home-tab" data-bs-toggle="pill" data-bs-target="#v-pills-home" type="button" role="tab" aria-controls="v-pills-home" aria-selected="true">Home</button>
        <button class="nav-link" id="v-pills-profile-tab" data-bs-toggle="pill" data-bs-target="#v-pills-profile" type="button" role="tab" aria-controls="v-pills-profile" aria-selected="false">Profile</button>
        <button class="nav-link" id="v-pills-messages-tab" data-bs-toggle="pill" data-bs-target="#v-pills-messages" type="button" role="tab" aria-controls="v-pills-messages" aria-selected="false">Messages</button>
        <button class="nav-link" id="v-pills-settings-tab" data-bs-toggle="pill" data-bs-target="#v-pills-settings" type="button" role="tab" aria-controls="v-pills-settings" aria-selected="false">Settings</button>
    </div>
    <div class="tab-content" id="v-pills-tabContent">
        <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">Home</div>
        <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">Profile</div>
        <div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">Messages</div>
        <div class="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">Settings</div>
    </div>
</div>

MarketPlace.Application/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <div class="row">
        <div class="col-sm-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Buy</h5>
                    <p class="card-text">Buy a commodity. Call or Chat prospective Sellers here.</p>
                    <a href="@Url.Action("Index","Buy")" class="btn btn-primary">Buy Now</a>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Sell</h5>
                    <p class="card-text">Sell a commodity. Meet prospective Buyers here.</p>
                    <a href="@Url.Action("Index","Sell")" class="btn btn-primary">Sell Now</a>
                </div>
            </div>
        </div>
    </div>
</div>

MarketPlace.Application/Views/Home/Profile.cshtml
@model MarketPlace.Data.DataObjects.KycModels.KycViewModel
@inject IUrlHelper _urlHelper;
@inject IHttpContextAccessor _httpContext;
@{
    ViewData["Title"] = "Profile";
    var context = _httpContext.HttpContext;
    var baseUrl = $"{context.Request.Scheme}://{context.Request.Host}{context.Request.PathBase}";


}

<section style="background-color: #eee;">
    <div class="container py-5">
        @* <div class="row">
        <div class="col">
        <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
        <ol class="breadcrumb mb-0">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item"><a href="#">User</a></li>
        <li class="breadcrumb-item active" aria-current="page">User Profile</li>
        </ol>
        </nav>
        </div>
        </div> *@

        <div class="row">
            <div class="col-lg-4">
                <div class="card mb-4">
                    <div class="card-body text-center">
                        @if (!string.IsNullOrEmpty(Model.PassportName))
                        {
                            var imagePath = $"{baseUrl}/Images/" + Model.PassportName;
                            <img id="imgPassport" src="@imagePath" alt="avatar"
                                 class="rounded-circle img-fluid" style="width: 150px;">
                        }
                        else
                        {
                            <img id="imgPassport" src="" alt="Kindly upload your passport"
                                 class="rounded-circle img-fluid" style="width: 150px;">
                        }
                        <center>
                            <input type="file" style="width:70%; font-size:10px" id="passportFile" class="form-control" />
                        </center>
                        <h5 class="my-3">@Model.FirstName @Model.LastName</h5>
                        <p class="text-muted mb-1">@Model.ResidentialAddress</p>
                        <p class="text-muted mb-4">@Model.City</p>
                    </div>
                </div>
                <div class="card mb-4 mb-lg-0">
                    <div class="card-body p-0">
                        <ul class="list-group list-group-flush rounded-3">
                            <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                <i class="fas fa-globe fa-lg text-warning"></i>
                                <p class="mb-0">https://mdbootstrap.com</p>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                <i class="fab fa-github fa-lg" style="color: #333333;"></i>
                                <p class="mb-0">@Model.Phone</p>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                <i class="fab fa-twitter fa-lg" style="color: #55acee;"></i>
                                <p class="mb-0">@Model.User.Email</p>
                            </li>
                            @* <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                            <i class="fab fa-instagram fa-lg" style="color: #ac2bac;"></i>
                            <p class="mb-0">mdbootstrap</p>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                            <i class="fab fa-facebook-f fa-lg" style="color: #3b5998;"></i>
                            <p class="mb-0">mdbootstrap</p>
                            </li> *@
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="card mb-4">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">First Name</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0"><input asp-for="FirstName" type="text" class="form-control" /></p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Last Name</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0"><input asp-for="LastName" type="text" class="form-control" /></p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Email</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0"><input type="email" asp-for="Email" class="form-control" readonly /> </p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Phone</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0"><input type="text" asp-for="Phone" class="form-control" /></p>
                            </div>
                        </div>
                        <hr />

                        <hr />
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">State</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">
                                    <select class="form-control" asp-for="State.Id" asp-items="Model.States">
                                        <option>Select State</option>
                                    </select>

                                </p>
                            </div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">City</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0"><input id="city" type="text" value="@Model.City" class="form-control" /></p>
                            </div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Address</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0"><textarea id="address" class="form-control">@Model.ResidentialAddress</textarea></p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">

                                </p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">
                                    <button class="btn btn-primary" onclick="SaveProfile(this)">Save Changes</button>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


@section Scripts {
    <script>

        function SaveProfile(e) {
            let obj = {
                "City": $('#city').val(),
                "StateId": $('#State_Id').val(),
                "CountryId": $('#Country_Id').val(),
                "ResidentialAddress": $('#address').val(),
                "FirstName": $('#FirstName').val(),
                "LastName": $('#LastName').val(),
                "Phone":$('#Phone').val()
            };

            console.log(obj);
            $.ajax({
                url: '@Url.Action("SaveProfile", "Home")',
                method: 'post',
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                data: JSON.stringify(obj),
                success: function (response) {
                    swal({
                        title: "Good job!",
                        text: response.message,
                        icon: "success",
                        button: "Ok!",
                    });
                },
                error: function (err) {
                    swal({
                        title: "Oops!",
                        text: "An error occurred while trying to save your entries",
                        icon: "error",
                        button: "Error",
                    });
                }
            });
        }


        const fileInput = document.getElementById('passportFile');
        const previewImg = document.getElementById('imgPassport');

        fileInput.addEventListener('change', function (event) {
            const file = event.target.files[0];

            if (file) {
                const reader = new FileReader();

                reader.addEventListener('load', function () {
                    previewImg.src = reader.result;
                });

                reader.readAsDataURL(file);

                const formData = new FormData();
                formData.append('file', file);

                // Create AJAX request
                const xhr = new XMLHttpRequest();
                xhr.open('POST', '@Url.Action("UploadPassport", "Home")', true);
                xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');

                xhr.onload = function () {
                    if (xhr.status === 200) {
                        console.log('File uploaded successfully');
                    } else {
                        console.error('File upload failed');
                    }
                };

                xhr.send(formData);
            }
        });
    </script>
}

MarketPlace.Application/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewData["Title"] - MarketPlace Application</title>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Meta -->
    <meta name="description" content="The Market Place Team" />
    <meta name="author" content="The Market Place Team" />
    <link rel="canonical" href="https://www.bootstrap.gallery/">
    <meta property="og:url" content="https://www.bootstrap.gallery">
    <meta property="og:title" content="The Market Place Team">
    <meta property="og:description" content="The Market Place Team">
    <meta property="og:type" content="Website">
    <meta property="og:site_name" content="The Market Place Team">
    <link rel="shortcut icon" href="~/assets/images/favicon.svg" />
    <!-- Bootstrap css -->
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css" />
    <!-- Bootstrap font icons css -->
    <link rel="stylesheet" href="~/assets/fonts/bootstrap/bootstrap-icons.css" />
    <!-- Main css -->
    <link rel="stylesheet" href="~/assets/css/main.min.css" />
    <!-- Login css -->
    <link rel="stylesheet" href="~/assets/css/login.css" />

    <style rel="stylesheet" type="text/css">
            .form-control {
            border: 1px solid #c8d0da;
            color: #232629;
            background-color: #fff;
             }
    </style>
</head>
<body class="login-container">
	<!-- Login box start -->
	<div class="container">
		@RenderBody()
	</div>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>